let questionsArray = [
    {
      "category": "Geografia",
      "pytanie": "Attyka, Epir, Tesalia, to regiony którego państwa?",
      "odpA": "Hiszpanii",
      "odpB": "Grecji",
      "odpC": "Włoch",
      "odpD": "Turcji",
      "popOdp": "B"
    },
    {
      "category": "Muzyka",
      "pytanie": "Ile strun ma altówka",
      "odpA": "3",
      "odpB": "4",
      "odpC": "5",
      "odpD": "6",
      "popOdp": "B",
    },
    {
      "category": "Muzyka",
      "pytanie": "Pod jakim hotelem liścia dostał Roman Boski?",
      "odpA": "Pod Jubilatem",
      "odpB": "Pod Novotelem",
      "odpC": "Pod Marriotem",
      "odpD": "Pod Różą",
      "popOdp": "A",
    },
    {
      "category": "Świat",
      "pytanie": "W hymnie którego Państwa jest wzmianka o Polsce?",
      "odpA": "USA",
      "odpB": "Włoch",
      "odpC": "Szwecji",
      "odpD": "Hiszpanii",
      "popOdp": "A",
    },
    {
      "category": "Biologia",
      "pytanie": "Ile razy na minute bije serce wieloryba?",
      "odpA": "14 razy",
      "odpB": "9 razy",
      "odpC": "1 raz",
      "odpD": "5 razy",
      "popOdp": "B",
    },
    {
      "category": "Świat",
      "pytanie": "Jaki kraj jest największym na świecie producentem kakao?",
      "odpA": "Ghana",
      "odpB": "Indonezja",
      "odpC": "Wybrzeże Kości Słoniowej",
      "odpD": "Tajlandia",
      "popOdp": "C",
    },
    {
      "category": "Świat",
      "pytanie": "Skąd pochodzi kakao?",
      "odpA": "Z Indii",
      "odpB": "Z Australii",
      "odpC": "Z Afryki",
      "odpD": "Z Ameryki",
      "popOdp": "D",
    },
    {
      "category": "Świat",
      "pytanie": "Kiedy odlano pierwszą tabliczkę czekolady?",
      "odpA": "W 1742 roku",
      "odpB": "W 1842 roku",
      "odpC": "W 1642 roku",
      "odpD": "W 1542 roku",
      "popOdp": "B",
    },
    {
      "category": "Chemia",
      "pytanie": "Co zawierała oryginalna recetura Pepsi Coli?",
      "odpA": "Kokainę",
      "odpB": "Enzym Trawienny",
      "odpC": "Saletrę potasową",
      "odpD": "Mefedron",
      "popOdp": "B",
    },
    {
      "category": "Świat",
      "pytanie": "W jakim kraju usmażono największą jajecznice?",
      "odpA": "W Rosji",
      "odpB": "W Anglii",
      "odpC": "W USA",
      "odpD": "W Polsce",
      "popOdp": "D",
    },
    {
      "category": "Ciekawostki",
      "pytanie": "Ile miesięcy budowano Titanica?",
      "odpA": "26 miesięcy",
      "odpB": "30 miesięcy",
      "odpC": "32 miesiące",
      "odpD": "34 miesiące",
      "popOdp": "B",
    },
    {
      "category": "Ciekawostki",
      "pytanie": "Na pokładzie Titanica było 109 dzieci, ile powróciło na ląd?",
      "odpA": "24",
      "odpB": "30",
      "odpC": "56",
      "odpD": "84",
      "popOdp": "C",
    },
    {
      "category": "Ciekawostki",
      "pytanie": "Z Titanica uratowano 771 pasażerów. Ilu z nich to mężczyźni?",
      "odpA": "58",
      "odpB": "122",
      "odpC": "175",
      "odpD": "206",
      "popOdp": "A",
    },
    {
      "category": "Kulinaria",
      "pytanie": "Bouillabaisse to potrawa z której słynie...",
      "odpA": "Wenecja",
      "odpB": "Praga",
      "odpC": "Genewa",
      "odpD": "Marsylia",
      "popOdp": "D",
    },
    {
      "category": "Muzyka",
      "pytanie": 'Słynny Polski raper, który zrewolucjonizował polską scene muzyczną utworem "Tatuażyk" to...',
      "odpA": "Quebonafide",
      "odpB": "Blacha 2115",
      "odpC": "Sentino",
      "odpD": "Białas",
      "popOdp": "C",
    },
    {
      "category": "Zwierzęta",
      "pytanie": 'Jakie jest najciższe zwierze lądowe na świecie?',
      "odpA": "Słoń",
      "odpB": "Żyrafa",
      "odpC": "Wielbłąd",
      "odpD": "Hipopotam",
      "popOdp": "A",
    },
    {
      "category": "Świat",
      "pytanie": 'Gdzie jest najdłuższy most na świecie?',
      "odpA": "Chiny",
      "odpB": "USA",
      "odpC": "Tajwan",
      "odpD": "Indie",
      "popOdp": "A",
    },
    {
      "category": "Geografia",
      "pytanie": 'Który kraj ma największą populacje na świecie?',
      "odpA": "Indie",
      "odpB": "Chiny",
      "odpC": "USA",
      "odpD": "Rosja",
      "popOdp": "B",
    },
    {
      "category": "Geografia",
      "pytanie": 'Jakie jest najwięsze miasto pod względem powierzchni na świecie?',
      "odpA": "Nowy Jork",
      "odpB": "Moskwa",
      "odpC": "Paryż",
      "odpD": "Tokyo",
      "popOdp": "A",
    },
    {
      "category": "Geografia",
      "pytanie": 'Najzimniejsze miejsce na świecie to...',
      "odpA": "Oymyakon",
      "odpB": "Antarctica",
      "odpC": "Loyalona",
      "odpD": "Moskwa",
      "popOdp": "A",
    },
    {
      "category": "Geografia",
      "pytanie": 'Najcieplejsze miejsce na świecie to...',
      "odpA": "Cern",
      "odpB": "Lut Desert",
      "odpC": "Bangkok",
      "odpD": "Dallol",
      "popOdp": "D",
    },
    {
      "category": "Geografia",
      "pytanie": 'Które miasto ma największą populacje na świcie?',
      "odpA": "Mumbai - Indie",
      "odpB": "Nowy Jork - USA",
      "odpC": "Tokyo - Japonia",
      "odpD": "Londyn - Wielka Brytania",
      "popOdp": "C",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Największa biblioteka na świecie mieści się w?',
      "odpA": "Indiach",
      "odpB": "USA",
      "odpC": "Kanadzie",
      "odpD": "Rosji",
      "popOdp": "B",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Najbardziej deszczowe miejsce na świcie to?',
      "odpA": "Lloro w Kolumbii",
      "odpB": "Loprez de Micay w Kolumbii",
      "odpC": "Cherrapunzi w Indiach",
      "odpD": "Mawsynram w Indiach",
      "popOdp": "D",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Najmniejsze państwo świata to?',
      "odpA": "Watykan",
      "odpB": "Monaco",
      "odpC": "Nauru",
      "odpD": "San Marino",
      "popOdp": "A",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Ile jest planet w układzie słonecznym?',
      "odpA": "10",
      "odpB": "9",
      "odpC": "8",
      "odpD": "7",
      "popOdp": "C",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Ile jest planet w układzie słonecznym?',
      "odpA": "10",
      "odpB": "9",
      "odpC": "8",
      "odpD": "7",
      "popOdp": "C",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Jaka jest najmniejsza planeta w naszym układzie słonecznym?',
      "odpA": "Merkury",
      "odpB": "Mars",
      "odpC": "Ziemia",
      "odpD": "Jowisz",
      "popOdp": "A",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Jaka jest trzecia najbliższa planeta od słonca?',
      "odpA": "Wenus",
      "odpB": "Ziemia",
      "odpC": "Mars",
      "odpD": "Merkury",
      "popOdp": "B",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Jak nazywał się statek kosmiczny, którym pierwsi ludzie wylądowali na księżycu?',
      "odpA": "Apollo 9",
      "odpB": "Apollo 10",
      "odpC": "Apollo 11",
      "odpD": "Apollo 12",
      "popOdp": "C",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Pierwszy człowiekiem na księżycu był?',
      "odpA": "Yuri Gagarin",
      "odpB": "Rakesh Sharma",
      "odpC": "Neil Alden Armstrong",
      "odpD": "Michael Collins",
      "popOdp": "C",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Pierwsza kobieta, która była na księżycu to?',
      "odpA": "Margaret Thatcher",
      "odpB": "Junko Tabei",
      "odpC": "Sunita Williams",
      "odpD": "Velentina Tereshkova",
      "popOdp": "D",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Pierwszym statkiem bezzałogowym, który wylądował na Marsie był?',
      "odpA": "Sputnik",
      "odpB": "Apollo 12",
      "odpC": "GSLV-5",
      "odpD": "Viking-1",
      "popOdp": "D",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Kto był pierwszym człowiekiem, który poleciał w kosmos?',
      "odpA": "Yuri Gagarin",
      "odpB": "Rakesh Sharma",
      "odpC": "Neil Alden Armstrong",
      "odpD": "Michael Collins",
      "popOdp": "A",
    },
    {
      "category": "Astronomia",
      "pytanie": 'Kiedy Neil Armstrong and Buzz Aldrin wylądowali na księżycu?',
      "odpA": "11 września",
      "odpB": "12 lipca",
      "odpC": "5 maja",
      "odpD": "21 lipca",
      "popOdp": "D",
    }

    //36 pytan
    ,
    {
      "category": "Świat",
      "pytanie": 'Krowa jest zwierzęciem narodowym, którego kraju?',
      "odpA": "Indii",
      "odpB": "Nepalu",
      "odpC": "Bhutanu",
      "odpD": "Sri Lanki",
      "popOdp": "B",
    },
    {
      "category": "Sport",
      "pytanie": 'Który z tych sportowców posiada najwięcej złotych medali olimpijskich?',
      "odpA": "Larisa Latynina",
      "odpB": "Michael Phelps",
      "odpC": "Usain Bolt",
      "odpD": "Paavo Nurmi",
      "popOdp": "B",
    },
    {
      "category": "Sport",
      "pytanie": 'Ile jest okręgów z symbolu igrzysk olimpijskich?',
      "odpA": "4",
      "odpB": "5",
      "odpC": "6",
      "odpD": "7",
      "popOdp": "B",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Wynalazcą telefonu jest?',
      "odpA": "Alexander Graham Bell",
      "odpB": "Nikolay Banardos",
      "odpC": "Issac Newton",
      "odpD": "Francis Beaufort",
      "popOdp": "A",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'John Vincent Atanasoff jest uznawany za wynalazce...',
      "odpA": "Elektronicznego komputera",
      "odpB": "Radio",
      "odpC": "Telewizora",
      "odpD": "Teleskopu",
      "popOdp": "A",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Wynalazcą drukarki 3D jest...',
      "odpA": "Ted Hoff",
      "odpB": "John Wesley Hyatt",
      "odpC": "Chuck Hull",
      "odpD": "Ralph H. Baer",
      "popOdp": "C",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Kto odkrył insuline?',
      "odpA": "Arya Bhatt",
      "odpB": "John Hopkins",
      "odpC": "Frederick Banting",
      "odpD": "Żaden z nich",
      "popOdp": "C",
    },
    {
      "category": "Ciekawostki",
      "pytanie": 'Obywatel, którego kraju nigdy nie zdobył nagrody Nobla?',
      "odpA": "Iraku",
      "odpB": "Iranu",
      "odpC": "Korei Północnego",
      "odpD": "Mjanmy",
      "popOdp": "C",
    }
  ]